name: CI
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ftp deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.cluster029.hosting.ovh.net
        FTP_USERNAME: souterrefn
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./
        REMOTE_DIR: www
        ARGS: --delete --transfer-all
